local black = "#000000"
local light_yellow = "#f9eab3"
local highlights_fixes = {
	MiniStatuslineModeNormal = { fg = black, bg = light_yellow },
	Identifier = { fg = "#000000" },
	["variable"] = { fg = black },
	["@variable"] = { fg = black },
}
local colors = {
	-- content here will not be touched
	-- PATCH_OPEN
Normal = {fg = "#033016", bg = "#F0F0F0"},
NeogitDiffContext = {link = "Normal"},
NeogitDiffContextHighlight = {link = "Normal"},
ALEError = {fg = "#c4331d", bold = true},
ALEErrorSign = {fg = "#c4331d", bold = true},
ALEWarning = {fg = "#b37f02", bold = true},
ALEWarningSign = {fg = "#b37f02", bold = true},
BlackOnLightYellow = {fg = "#000000", bg = "#f9eab3"},
Bold = {fg = "#000000", bold = true},
ColorColumn = {bg = "#eeeeee"},
Comment = {fg = "#3779B3"},
EyelinerDimmed = {link = "Comment"},
FoldColumn = {link = "Comment"},
Folded = {link = "Comment"},
MiniPickBorderText = {link = "Comment"},
hamlDocType = {link = "Comment"},
markdownCodeBlock = {link = "Comment"},
podCommand = {link = "Comment"},
rustCommentBlockDoc = {link = "Comment"},
rustCommentLineDoc = {link = "Comment"},
yardComment = {link = "Comment"},
Conceal = {},
Constant = {fg = "#000000"},
Type = {link = "Constant"},
VimIsCommand = {link = "Constant"},
rubyConstant = {link = "Constant"},
vimGroup = {link = "Constant"},
vimHiGroup = {link = "Constant"},
Cursor = {bg = "#000000"},
CursorLine = {bg = "#D4D4D4"},
CursorColumn = {link = "CursorLine"},
CursorLineNr = {fg = "#279155", italic = true},
DiagnosticDeprecated = {},
DiagnosticError = {fg = "#c4331d", bold = true},
DiagnosticFloatingError = {fg = "#c4331d", bold = true},
DiagnosticFloatingHint = {fg = "#000000", bold = true},
DiagnosticFloatingInfo = {fg = "#1561b8", bold = true},
DiagnosticFloatingWarn = {fg = "#b37f02", bold = true},
DiagnosticHint = {fg = "#5e5e5e", bold = true},
DiagnosticInfo = {fg = "#1561b8", bold = true},
DiagnosticUnderlineError = {sp = "#c4331d", underline = true},
LspDiagnosticsUnderlineError = {link = "DiagnosticUnderlineError"},
DiagnosticUnderlineWarn = {sp = "#b37f02", underline = true},
LspDiagnosticsUnderlineWarning = {link = "DiagnosticUnderlineWarn"},
DiagnosticWarn = {fg = "#b37f02", bold = true},
DiffAdd = {bg = "#dfeacc"},
NeogitDiffAdd = {link = "DiffAdd"},
diffAdded = {link = "DiffAdd"},
DiffChange = {bg = "#eeeeee"},
diffChanged = {link = "DiffChange"},
DiffDelete = {fg = "#c4331d"},
NeogitDiffDelete = {link = "DiffDelete"},
diffRemoved = {link = "DiffDelete"},
DiffText = {bg = "#f9eab3"},
DiffviewCursorLine = {bg = "#e6e6e6", bold = true},
DiffviewDiffAddAsDelete = {bg = "#f2d3cd"},
DiffviewDiffDelete = {fg = "#e6e6e6"},
DiffviewDiffDeleteDim = {fg = "#e6e6e6"},
DiffviewFilePanelDeletions = {fg = "#c4331d"},
DiffviewFilePanelFileName = {fg = "#000000"},
DiffviewFilePanelInsertions = {fg = "#1C5708"},
DiffviewFilePanelPath = {fg = "#5c21a5"},
DiffviewFilePanelRootPath = {fg = "#5c21a5"},
DiffviewFilePanelTitle = {fg = "#000000", bold = true},
DiffviewStatusAdded = {fg = "#1C5708", bold = true},
DiffviewStatusCopied = {fg = "#1C5708", bold = true},
DiffviewStatusDeleted = {fg = "#c4331d", bold = true},
DiffviewStatusModified = {fg = "#b37f02", bold = true},
Directory = {fg = "#5c21a5"},
htmlLink = {link = "Directory"},
javaAnnotation = {link = "Directory"},
Disabled = {},
EndOfBuffer = {fg = "#f2f2f2", bg = "#f2f2f2"},
ErrorMsg = {fg = "#FF0000"},
Error = {link = "ErrorMsg"},
gitCommitOverflow = {link = "ErrorMsg"},
EyelinerPrimary = {fg = "#c4331d", bold = true},
EyelinerSecondary = {fg = "#b37f02", bold = true},
FlashLabel = {fg = "#000000", bg = "#f9db70", bold = true},
FlashPromptIcon = {bold = true},
FloatBorder = {fg = "#cccccc"},
CccFloatBorder = {link = "FloatBorder"},
SnacksInputBorder = {link = "FloatBorder"},
FloatTitle = {fg = "#000000", bold = true},
SignColumn = {link = "FoldColumn"},
FugitiveblameHash = {fg = "#5c21a5"},
FugitiveblameTime = {fg = "#1561b8"},
Function = {fg = "#085191"},
makeTarget = {link = "Function"},
rubyFunction = {link = "Function"},
typescriptFunction = {link = "Function"},
GitSignsAdd = {fg = "#cccccc"},
GitSignsChange = {fg = "#cccccc"},
GitSignsDelete = {fg = "#cccccc"},
GitSignsStagedAdd = {fg = "#5e5e5e"},
GitSignsStagedChange = {fg = "#5e5e5e"},
GitSignsStagedDelete = {fg = "#5e5e5e"},
HopNextKey = {fg = "#000000", bg = "#f9db70", bold = true},
HopNextKey1 = {bg = "#f9eab3"},
HopNextKey2 = {bg = "#f9eab3"},
HopUnmatched = {},
Identifier = {fg = "#000000"},
cssProp = {link = "Identifier"},
htmlArg = {link = "Identifier"},
javaScriptMember = {link = "Identifier"},
netrwClassify = {link = "Identifier"},
perlPackageDecl = {link = "Identifier"},
rubyAttribute = {link = "Identifier"},
rubyMacro = {link = "Identifier"},
rustFuncCall = {link = "Identifier"},
rustModPath = {link = "Identifier"},
typescriptIdentifier = {link = "Identifier"},
xmlAttrib = {link = "Identifier"},
xmlTag = {link = "Identifier"},
xmlTagName = {link = "Identifier"},
["@attribute.rust"] = {link = "Identifier"},
Include = {fg = "#000000", bold = true},
InstanceVariable = {fg = "#5c21a5"},
inkoInstanceVariable = {link = "InstanceVariable"},
rubyInstanceVariable = {link = "InstanceVariable"},
["@variable.member.inko"] = {link = "InstanceVariable"},
["@variable.member.ruby"] = {link = "InstanceVariable"},
Keyword = {fg = "#BD001C"},
Boolean = {link = "Keyword"},
Label = {link = "Keyword"},
Statement = {link = "Keyword"},
StorageClass = {link = "Keyword"},
cssClassName = {link = "Keyword"},
cssIdentifier = {link = "Keyword"},
cssImportant = {link = "Keyword"},
cssTagName = {link = "Keyword"},
javaExternal = {link = "Keyword"},
javaScriptFunction = {link = "Keyword"},
javaScriptIdentifier = {link = "Keyword"},
javaStorageClass = {link = "Keyword"},
luaFunction = {link = "Keyword"},
markdownListMarker = {link = "Keyword"},
markdownOrderedListMarker = {link = "Keyword"},
pythonOperator = {link = "Keyword"},
rubyClass = {link = "Keyword"},
rubyDefine = {link = "Keyword"},
shFunctionKey = {link = "Keyword"},
sqlKeyword = {link = "Keyword"},
typescriptExceptions = {link = "Keyword"},
typescriptFuncKeyword = {link = "Keyword"},
["@constant.builtin.inko"] = {link = "Keyword"},
LightRedBackground = {bg = "#f2d3cd"},
LineNr = {fg = "#3779B3", italic = true},
LineNrAbove = {link = "LineNr"},
LineNrBelow = {link = "LineNr"},
LspReferenceTarget = {},
Macro = {fg = "#a55000"},
PreCondit = {link = "Macro"},
["@function.macro.rust"] = {link = "Macro"},
MatchParen = {bold = true},
MiniDiffSignAdd = {fg = "#cccccc"},
MiniDiffSignChange = {fg = "#cccccc"},
MiniDiffSignDelete = {fg = "#cccccc"},
MiniIconsAzure = {fg = "#1561b8"},
MiniIconsBlue = {fg = "#1561b8"},
MiniIconsCyan = {fg = "#007872"},
MiniIconsGreen = {fg = "#1C5708"},
MiniIconsGrey = {fg = "#5e5e5e"},
MiniIconsOrange = {fg = "#a55000"},
MiniIconsPurple = {fg = "#5c21a5"},
MiniIconsRed = {fg = "#c4331d"},
MiniIconsYellow = {fg = "#b37f02"},
MiniJump2dSpot = {fg = "#c4331d", bold = true},
MiniJump2dSpotAhead = {fg = "#c4331d", bold = true},
MiniPickBorder = {fg = "#cccccc"},
MiniPickBorderBusy = {link = "MiniPickBorder"},
MiniPickHeader = {fg = "#000000", bold = true},
MiniPickMatchCurrent = {bg = "#e6e6e6", bold = true},
MiniPickMatchMarked = {bold = true},
MiniPickMatchRanges = {fg = "#b37f02", bold = true},
MiniPickNormal = {fg = "#000000"},
MiniPickPrompt = {fg = "#000000"},
ModeMsg = {fg = "#000000", bold = true},
MoreMsg = {fg = "#000000"},
MsgSeparator = {fg = "#cccccc"},
NeogitBranch = {fg = "#1C5708", bold = true},
NeogitBranchHead = {link = "NeogitBranch"},
NeogitPopupBranchName = {link = "NeogitBranch"},
NeogitRemote = {link = "NeogitBranch"},
NeogitCommitViewHeader = {fg = "#b37f02", bold = true},
NeogitCursorLine = {bg = "#eeeeee"},
NeogitDiffAddHighlight = {link = "NeogitDiffAdd"},
NeogitDiffDeleteHighlight = {link = "NeogitDiffDelete"},
NeogitDiffHeader = {fg = "#000000", bold = true},
NeogitDiffHeaderHighlight = {link = "NeogitDiffHeader"},
NeogitFilePath = {fg = "#5c21a5"},
NeogitGraphBlue = {fg = "#1561b8"},
NeogitGraphBoldBlue = {fg = "#1561b8", bold = true},
NeogitGraphBoldCyan = {fg = "#007872", bold = true},
NeogitGraphBoldGray = {fg = "#5e5e5e", bold = true},
NeogitGraphBoldGreen = {fg = "#1C5708", bold = true},
NeogitGraphBoldOrange = {fg = "#a55000", bold = true},
NeogitGraphBoldPurple = {fg = "#5c21a5", bold = true},
NeogitGraphBoldRed = {fg = "#c4331d", bold = true},
NeogitGraphBoldWhite = {fg = "#000000", bold = true},
NeogitGraphBoldYellow = {fg = "#b37f02", bold = true},
NeogitGraphCyan = {fg = "#007872"},
NeogitGraphGray = {fg = "#5e5e5e"},
NeogitGraphGreen = {fg = "#1C5708"},
NeogitGraphOrange = {fg = "#a55000"},
NeogitGraphPurple = {fg = "#5c21a5"},
NeogitGraphRed = {fg = "#c4331d"},
NeogitGraphWhite = {fg = "#000000"},
NeogitGraphYellow = {fg = "#b37f02"},
NeogitHunkHeader = {fg = "#1561b8"},
NeogitHunkHeaderHighlight = {link = "NeogitHunkHeader"},
NeogitPopupOptionEnabled = {bg = "#dfeacc", bold = true},
NeogitPopupConfigEnabled = {link = "NeogitPopupOptionEnabled"},
NeogitPopupSwitchEnabled = {link = "NeogitPopupOptionEnabled"},
NeogitPopupOptionKey = {bold = true},
NeogitPopupActionKey = {link = "NeogitPopupOptionKey"},
NeogitPopupConfigKey = {link = "NeogitPopupOptionKey"},
NeogitPopupSwitchKey = {link = "NeogitPopupOptionKey"},
NonText = {fg = "#5e5e5e"},
FlashBackdrop = {link = "None"},
PounceGap = {link = "None"},
NormalFloat = {fg = "#000000"},
CccFloatNormal = {link = "NormalFloat"},
NotifyDEBUGBorder = {fg = "#cccccc"},
NotifyDEBUGIcon = {fg = "#5e5e5e"},
NotifyDEBUGTitle = {fg = "#5e5e5e"},
NotifyERRORBorder = {fg = "#cccccc"},
NotifyERRORIcon = {fg = "#c4331d"},
NotifyERRORTitle = {fg = "#c4331d"},
NotifyINFOBorder = {fg = "#cccccc"},
NotifyINFOIcon = {fg = "#1C5708"},
NotifyINFOTitle = {fg = "#1C5708"},
NotifyTRACEBorder = {fg = "#cccccc"},
NotifyTRACEIcon = {fg = "#5c21a5"},
NotifyTRACETitle = {fg = "#5c21a5"},
NotifyWARNBorder = {fg = "#cccccc"},
NotifyWARNIcon = {fg = "#a55000"},
NotifyWARNTitle = {fg = "#a55000"},
Number = {fg = "#1561b8"},
JavaScriptNumber = {link = "Number"},
SnacksPickerCol = {link = "Number"},
SnacksPickerRow = {link = "Number"},
SpecialKey = {link = "Number"},
cssColor = {link = "Number"},
inkoCommentInlineUrl = {link = "Number"},
OkMsg = {fg = "#009963"},
Operator = {fg = "#000000"},
dotKeyChar = {link = "Operator"},
javaScriptBraces = {link = "Operator"},
typescriptBraces = {link = "Operator"},
typescriptEndColons = {link = "Operator"},
typescriptLogicSymbols = {link = "Operator"},
Pmenu = {fg = "#000000", bg = "#ececec"},
PmenuMatch = {fg = "#b37f02", bold = true},
PmenuSbar = {bg = "#ececec"},
PmenuSel = {bg = "#e6e6e6", bold = true},
WildMenu = {link = "PmenuSel"},
PmenuThumb = {bg = "#e6e6e6"},
PounceAccept = {fg = "#000000", bg = "#f9db70", bold = true},
PounceAcceptBest = {link = "PounceAccept"},
PounceMatch = {bg = "#f9eab3"},
PounceUnmatched = {},
PreProc = {fg = "#000000"},
Question = {fg = "#000000"},
QuickFixLine = {bg = "#eeeeee", bold = true},
Regexp = {fg = "#a55000"},
inkoKeywordArgument = {link = "Regexp"},
rubyRegexp = {link = "Regexp"},
rubyRegexpCharClass = {link = "Regexp"},
rubyRegexpDelimiter = {link = "Regexp"},
rubyRegexpQuantifier = {link = "Regexp"},
rubyRegexpSpecial = {link = "Regexp"},
["@string.regexp"] = {link = "Regexp"},
Search = {bg = "#f9eab3"},
CurSearch = {link = "Search"},
IncSearch = {link = "Search"},
SnacksPickerDir = {fg = "#000000"},
SnacksPickerListCursorLine = {bg = "#e6e6e6", bold = true},
SnacksPickerMatch = {fg = "#b37f02", bold = true},
SnacksPickerPrompt = {fg = "#000000", bold = true},
SnippetTabstop = {},
SnippyPlaceholder = {link = "SnippetTabstop"},
Special = {fg = "#000000"},
SpellBad = {sp = "#c4331d", underline = true},
SpellCap = {sp = "#b37f02", underline = true},
SpellLocal = {sp = "#1561b8", underline = true},
SpellRare = {sp = "#5c21a5", underline = true},
perlStatementInclude = {link = "Statement"},
perlStatementPackage = {link = "Statement"},
StatusLine = {fg = "#000000", bg = "#f2f2f2"},
StatusLineNC = {fg = "#000000", bg = "#ececec"},
StatusLineTab = {fg = "#000000", bg = "#f2f2f2", bold = true},
String = {fg = "#00753B"},
Character = {link = "String"},
gitCommitSummary = {link = "String"},
jsonKeyword = {link = "String"},
rubyStringDelimiter = {link = "String"},
yamlPlainScalar = {link = "String"},
Symbol = {fg = "#a55000"},
rubySymbol = {link = "Symbol"},
TabLine = {fg = "#000000", bg = "#e6e6e6"},
TabLineFill = {fg = "#000000", bg = "#e6e6e6"},
TabLineSel = {fg = "#000000", bg = "#f2f2f2", bold = true},
TelescopeBorder = {fg = "#cccccc"},
TelescopeMatching = {fg = "#b37f02", bold = true},
TelescopeNormal = {fg = "#000000"},
TelescopePromptBorder = {fg = "#cccccc"},
TelescopePromptNormal = {fg = "#000000"},
TelescopePromptPrefix = {fg = "#000000", bold = true},
TelescopeSelection = {bg = "#e6e6e6", bold = true},
TelescopeTitle = {fg = "#000000", bold = true},
Title = {fg = "#000000", bold = true},
NeogitPopupSectionTitle = {link = "Title"},
SnacksInputTitle = {link = "Title"},
Todo = {fg = "#5e5e5e", bold = true},
VimCommentTitle = {link = "Todo"},
javaDocParam = {link = "Todo"},
javaDocTags = {link = "Todo"},
podCmdText = {link = "Todo"},
podVerbatimLine = {link = "Todo"},
yardType = {link = "Todo"},
yardTypeList = {link = "Todo"},
Underlined = {underline = true},
VertSplit = {fg = "#cccccc"},
Visual = {fg = "#F0F0F0", bg = "#033016"},
WarningMsg = {fg = "#9B5A22"},
WhiteOnBlue = {fg = "#ffffff", bg = "#1561b8"},
WhiteOnOrange = {fg = "#ffffff", bg = "#a55000"},
WhiteOnRed = {fg = "#ffffff", bg = "#c4331d"},
WhiteOnYellow = {fg = "#ffffff", bg = "#b37f02"},
Whitespace = {fg = "#cccccc"},
WinBar = {fg = "#000000", bold = true},
WinBarFill = {fg = "#cccccc"},
WinBarNc = {fg = "#000000", bold = true},
WinSeparator = {fg = "#cccccc"},
Yellow = {fg = "#b37f02", bold = true},
sassClass = {link = "cssClassName"},
["@type.css"] = {link = "cssClassName"},
cssCustomProp = {fg = "#5c21a5"},
["@variable.css"] = {link = "cssCustomProp"},
sassId = {link = "cssIdentifier"},
["@tag.css"] = {link = "cssIdentifier"},
cssPseudoClass = {fg = "#a55000", bold = true},
cssPseudoClassId = {link = "cssPseudoClass"},
["@constant.css"] = {link = "cssTagName"},
diffFile = {fg = "#000000", bold = true},
diffLine = {fg = "#1561b8"},
hamlClass = {fg = "#000000"},
hamlId = {fg = "#000000"},
hamlTag = {fg = "#000000", bold = true},
htmlBold = {bold = true},
htmlItalic = {italic = true},
htmlTag = {fg = "#000000", bold = true},
htmlScriptTag = {link = "htmlTag"},
htmlSpecialTagName = {link = "htmlTag"},
htmlTagName = {link = "htmlTag"},
inkoCommentBold = {fg = "#5e5e5e", bold = true},
inkoCommentItalic = {fg = "#5e5e5e", italic = true},
inkoCommentTitle = {fg = "#5e5e5e", bold = true},
javaCommentTitle = {link = "javaComment"},
markdownCode = {link = "markdownCodeBlock"},
markdownUrl = {fg = "#1561b8"},
rubyModule = {link = "rubyClass"},
rubyClassVariable = {link = "rubyInstancevariable"},
["@string.special.symbol.ruby"] = {link = "rubySymbol"},
variable = {fg = "#000000"},
["@comment.warning.gitcommit"] = {fg = "#c4331d", bold = true},
["@keyword"] = {fg = "#BD001C"},
["@markup.link"] = {fg = "#1561b8"},
["@markup.link.gitcommit"] = {fg = "#1C5708", bold = true},
["@operator"] = {fg = "#000000"},
["@property.json"] = {bold = true},
["@string.special.url.gitcommit"] = {fg = "#000000"},
["@tag"] = {fg = "#000000"},
["@text.emphasis"] = {italic = true},
["@text.reference"] = {fg = "#5c21a5"},
["@text.strong"] = {bold = true},
["@text.uri"] = {fg = "#1561b8"},
["@variable"] = {fg = "#000000"},
["@variable.builtin"] = {bold = true},
["@variable.parameter.reference"] = {fg = "#a55000"},
	-- PATCH_CLOSE
	-- content here will not be touched
	["variable"] = { fg = black },
	["@variable"] = { fg = black },
}

vim.cmd("let g:colors_name='wasserbaum'")

-- apply highlight groups
for group, attrs in pairs(colors) do
	vim.api.nvim_set_hl(0, group, attrs)
end
for group, opts in pairs(highlights_fixes) do
	vim.api.nvim_set_hl(0, group, opts)
end
